### ISSUE TITLE
Swift 4.2 compatibillity

### ISSUE THREAD

**Issue by edwardmp** [chrisdhaan/CDMarkdownKit#15]
## What did you do?

Used CDMarkdownKit in a Swift 4.2/Xcode 10 project

## What did you expect to happen?

It should not yield any errors or warnings

## What happened instead?

It yields numerous compile errors, primarily related to `NSAttributedStringKey` & `UIFontDescriptorSymbolicTraits`.

> CDMarkdownKit/Source/CDFont.swift:33:55: 'UIFontDescriptorSymbolicTraits' has been renamed to 'UIFontDescriptor.SymbolicTraits'
CDMarkdownKit/Source/CDMarkdownStyle.swift:50:24: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownStyle.swift:53:24: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownStyle.swift:56:24: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownStyle.swift:59:24: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownSyntax.swift:88:50: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownSyntax.swift:112:47: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownLink.swift:71:39: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownList.swift:108:39: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownParser.swift:193:39: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownParser.swift:196:39: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownParser.swift:199:39: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownParser.swift:202:39: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownHeader.swift:118:24: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownImage.swift:76:39: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownLabel.swift:333:39: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2
CDMarkdownKit/Source/CDMarkdownLabel.swift:390:60: 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key'
/Foundation.NSAttributedStringKey:2:18: 'NSAttributedStringKey' was obsoleted in Swift 4.2

I can submit a PR for this, but I'd like to hear from @chrisdhaan what approach he wants to follow.
Possible approaches:

1. Drop pre-Swift 4.2 support completely
2. Make Swift 4.2 support available through a new branch
3. Use conditional compile directives to include different code based on used Swift version.

The last option is probably the right one judging on past use of this approach. But I'd like to know for certain before I submit a PR to avoid unnecessary work.

## CDMarkdownKit Environment

**CDMarkdownKit version:**  1.2.0
**Xcode version:**  10.0
**Swift version:** 4.2
**Platform(s) running CDMarkdownKit:** iOS 12
**macOS version running Xcode:** 10.13.6

**Comment by chrisdhaan** [comment]
Fixed with version `1.2.1`. Closing issue.
