### ISSUE TITLE
CDMarkdownTextView: Load local images 

### ISSUE THREAD

**Issue by karstengresch** [chrisdhaan/CDMarkdownKit#2]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDMarkdownKit/blob/master/CONTRIBUTING.md).

## What did you do?

Tried to use a local image (added to main bundle) referencing it via:

```
![my image](my-image.png)
![my image](./my-image.png)
![my image](file://my-image.png)
![my image](file://./my-image.png)
```

## What did you expect to happen?

The image should at least once be loaded like an external image e.g.

```
![my external image](http://www.christopherdehaan.me/public/img/circle-hover.png)
```

which works fine.

## What happened instead?

No image loaded.

Instead, console told about a _NSURLConnection finished with error - code -1002_ error. IIUC this is a not supported protocol.

## CDMarkdownKit Environment

**CDMarkdownKit version:** 0.9.7  
**Xcode version:** 9.2 (9C40b) 
**Swift version:**  4.0.3
**Platform(s) running CDMarkdownKit:** iOS Simulator w/ iOS 11.2 (15C107) 
**macOS version running Xcode:**: 10.13.2 (17C205)

I used CDMarkdownTextView and could successfully load a local image with:

```swift

let myImage = UIImage(named: "my-image.png")
let attachment: NSTextAttachment = NSTextAttachment()
attachment.image = thumbnailImage
let attributedImageString: NSAttributedString = NSAttributedString(attachment: attachment)
cdMarkdownTextView.textStorage.append(attributedImageString)
```

Rough guess it's related to CDMarkdownImage's url handling.

## Demo Project

TBD, matter of time...

**Comment by chrisdhaan** [comment]
@karstengresch this is a good find. I see you opened a PR with a proposed solution. I'll get it happy so it works with the tests and hopefully have a new version up this weekend.

**Comment by karstengresch** [comment]
Hi @chrisdhaan - thanks very much!

**Comment by chrisdhaan** [comment]
@karstengresch the local image loading has been pushed to master.
