### ISSUE TITLE
Add possibility to use multiple \n in a row

### ISSUE THREAD

**Issue by MatyashDen** [chrisdhaan/CDMarkdownKit#26]
Thank you a lot for this library, i want to suggest small improvement that will be very helpful
Right now i can't use multiple `\n` in a row, because library replacing all consecutive `\n` into one `\n`
It can be solved adding bool flag in constructor which says if parser should replace `\n` or not

**Comment by MatyashDen** [comment]
@chrisdhaan

**Comment by barMapprosing** [comment]
We'll be glad to have this feature too! Please add it 👍

**Comment by chrisdhaan** [comment]
@MatyashDen @barMapprosing apologies for the super delayed response. I will get to this soon

**Comment by chrisdhaan** [comment]
@MatyashDen @barMapprosing addressed with PR #38 and available in version `2.3.0`
