### ISSUE TITLE
Link not clickable

### ISSUE THREAD

**Issue by adeds** [chrisdhaan/CDMarkdownKit#39]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDMarkdownKit/blob/master/CONTRIBUTING.md).

## What did you do?

I've tried the sample project, then I create and render a simple markdown, like "This *framework* helps **with** parsing `markdown` with [Link](https://google.com)."

## What did you expect to happen?

the `Link` is clickable

## What happened instead?

it is not clickable because `displayActionController` is not triggered <- `selectedURLRange` = nil <- `boundingReact` is not contains the `correctLocation`

<img width="703" alt="image" src="https://user-images.githubusercontent.com/23008913/197502227-2be22ac4-0ce1-4ac2-b342-f3502f7f7fbf.png">

<img width="978" alt="image" src="https://user-images.githubusercontent.com/23008913/197502260-817d3e2c-fc42-4415-8680-1abae7c96116.png">

## CDMarkdownKit Environment

**CDMarkdownKit version:**  2.3.0
**Xcode version:**  14.0.1
**Swift version:**  swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 **clang-1400.0.29.50)**
**Platform(s) running CDMarkdownKit:**  iOS
**macOS version running Xcode:** 12.6

**Comment by ilgaputra15** [comment]
I had the same problem if using `CDMarkdownLabel`. You can try using `UITextView` with `non editable` configuration, and use UITextViewDelegate to handle redirect `link`

**Configuration**
<img width="662" alt="Screen Shot 2022-10-25 at 11 30 16" src="https://user-images.githubusercontent.com/37990848/197683513-45517ae8-5746-4275-a6f4-976e0736f961.png">

<img width="644" alt="Screen Shot 2022-10-25 at 11 41 01" src="https://user-images.githubusercontent.com/37990848/197684249-dab7a9de-26f1-4169-be91-09ba1c95b601.png">


**Result**

https://user-images.githubusercontent.com/37990848/197683855-3ba436a4-fc67-4763-8719-05d35591dee9.mp4

**Comment by adeds** [comment]
Works like a charm!

thanks a lot @ilgaputra15
