### ISSUE TITLE
Paragraph Styling in CDMarkdownKit

### ISSUE THREAD

**Issue by tklucher** [chrisdhaan/CDMarkdownKit#4]
## What did you do?

Proposal for controlling the paragraph styling in CDMarkdownKit

I looked into paragraph styling that was in the old pull request and really liked his solution for paragraph styling. The only changes I made were the math to do number of lines before and after and exposing several variable for configuration. I think there might need to be some work done to pass the paragraph style along to certain classes like `CDMarkdownQuote.swift` as the default styling may look weird after you add the Quote style.

```
open var linesBeforeParagraph: CGFloat = 0
open var linesAfterParagraph:  CGFloat = 1
open var lineSpacing:          CGFloat = 1.38
```

```
let paraStyle = NSMutableParagraphStyle()
paraStyle.paragraphSpacingBefore = font.pointSize * linesBeforeParagraph
paraStyle.paragraphSpacing = font.pointSize * linesAfterParagraph
paraStyle.lineSpacing = lineSpacing
attributedString.addAttribute(NSAttributedStringKey.paragraphStyle, value: paraStyle, range: range)
```

## CDMarkdownKit Environment

**CDMarkdownKit version: 1.0.0**  
**Xcode version: Current**  
**Swift version: 4.0**  
**Platform(s) running CDMarkdownKit: Tested with iOS**  
**macOS version running Xcode: Have not tested for macOS**

## Demo Project

[Demo Example](https://github.com/visvateam/CDMarkdownKit/blob/master/Source/CDMarkdownParser.swift)

**Comment by tklucher** [comment]
As part of this feature request I think we should also take a look at the BlockQuote. I tried using paragraph styles there as well and really liked the result. Though I don't feel like this part is complete as I feel like it needs to be a bit more customizable and the paragraph styling in the parser needs to be shared with this class in some logical way that I have not figured out yet:

```
open func addFullAttributes(_ attributedString: NSMutableAttributedString, range: NSRange, level: Int) {
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.headIndent = indent
        paragraphStyle.tabStops = [NSTextTab(textAlignment: .left, location: paragraphStyle.headIndent, options: [:])]
        paragraphStyle.paragraphSpacing = font?.pointSize ?? 12.0
        attributedString.addAttribute(NSAttributedStringKey.paragraphStyle, value: paragraphStyle, range: range)
}
```

[Demo Example](https://github.com/visvateam/CDMarkdownKit/blob/master/Source/CDMarkdownQuote.swift)

**Comment by chrisdhaan** [comment]
@tklucher I started working on this today. Hoping to finish it up soon and push `1.0.0`. After that will be Swift 4 support.

**Comment by chrisdhaan** [comment]
@tklucher I've finished exposing paragraph styling on each type. I will either commit today or tomorrow. If afterwards you still feel that BlockQuote needs another look can you open a separate feature request?

**Comment by tklucher** [comment]
@chrisdhaan Sounds good. I am also going to work on ordered list in the coming weeks. I found that using the paragraph style with spacing after paragraph causes an ordered list to be super spaced out. The parser does not currently parse for ordered list so I might have it parse for that and then change the style on only those lines. Still not sure but I like the idea of paragraph style overall.

**Comment by chrisdhaan** [comment]
Yeah I think paragraph style was a good feature. I think it'll be rare that users of the framework will have to change paragraph style on several different markdown element types but I'm happy to give users the power too. Also if you find any default paragraph styles you really like for specific element types please share them.

Feel free to open BlockQuote and OrderedList as separate GitHub Issue feature requests.

Do I have your permission to close out this issue? The code is committed to master.

**Comment by tklucher** [comment]
@chrisdhaan It looks awesome! Yea feel free to close this. I plan to merge this code into my fork as soon as the swift 4 stuff is committed. Then I will take a look at the other elements and create any new issues if they require it. I am actually going to take a crack at writing the Ordered list element so I might do that as a pull request. I just have to sort out another repo to do that in, because the image changes I made for our app should never go into the codebase as it is a hack for a specific solution.
